version: "3"

services:     
  hackertrail:
    container_name: hackertrail
    build: HackerTrailAssessment
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./HackerTrailAssessment:/hackertrailassessment
    ports:
      - "8000:8000"