# Generated by Django 2.2.1 on 2019-05-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_priority', models.IntegerField()),
                ('target_date', models.DateField()),
                ('product_area', models.CharField(choices=[('Assessments', 'Assessments'), ('Billing', 'Billing'), ('Recruit', 'Recruit'), ('Reports', 'Reports')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestAPI.Client')),
            ],
        ),
    ]
